
railslink1 = Link.create!(:title => "Rails Guide", :url => "http://www.railsguide.com")

railslink2 = Link.create!(:title => "Stack Overflow", :url => "http://www.stackoverflow.com")
railslink3 = Link.create!(:title => "PostGres", :url => "http://www.postgres.com")
railslink4 = Link.create!(:title => "Steps for Installfest", :url => "https://gist.github.com/rsofaer/7952112")
railslink5 = Link.create!(:title => "Living in the Terminal", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/living_in_the_command_line.md")
railslink6 = Link.create!(:title => "Git Lesson", :url => "https://gist.github.com/jackieiscool/c871c86dc46ab0fadd37")
railslink7 = Link.create!(:title => "Ruby Overview, Part1", :url => "https://gist.github.com/Colt/9938071")
railslink8 = Link.create!(:title => "Ruby Overview, Part2", :url => "https://gist.github.com/Colt/10009194")
railslink9 = Link.create!(:title => "Living in the Command Line", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/Terminal/living_in_the_command_line.md")
railslink10 = Link.create!(:title => "Intro to Ruby Lesson", :url => "https://draftin.com/documents/296123?token=AiOl8kl4BD78EDQcg3Z-XOpyR1xIvVSl8Nesv82ioTmDvRoZyNdzjbCZQpwLn7K0N7aQQ9iO74_nsKyNE6NyhmU")
railslink11 = Link.create!(:title => "Intro to Ruby Lab", :url => "https://draftin.com/documents/296134?token=MSjniIDkxQkQ55Uf30ZnVn-gRrulFA21R4gNPL8yGm4J58QiNFBDOJcH4diZKbgPRt4D6ICpx-KdsKfaDbPLo6Q")
railslink12 = Link.create!(:title => "Into to Git notes", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/Git/intro_to_git_and_github.md")
railslink13 = Link.create!(:title => "Git Lab", :url => "https://gist.github.com/jackieiscool/0b4ea411f523e541244e")
railslink14 = Link.create!(:title => "Git clone lab", :url => "https://gist.github.com/jackieiscool/0b4ea411f523e541244e")
railslink15 = Link.create!(:title => "Arrays & Hashes", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/ArraysAndHashes/ruby_arrays_and_hashes.md")
railslink16 = Link.create!(:title => "Arrays & Hashes lab", :url =>  "https://github.com/wdi-sf-march-2014/mta_hashes_and_arrays_lab")
railslink17 = Link.create!(:title => "Method & Blocks notes", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/methods_blocks/ruby_custom_methods.md")
railslink18 = Link.create!(:title => "Method & Blocks Exercises", :url => "https://github.com/wdi-sf-march-2014/notes/tree/master/methods_blocks")
railslink19 = Link.create!(:title => "Objects & Classes", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/ObjectsAndClasses/ObjectsAndClasses.md")
railslink20 = Link.create!(:title => "Objects & Classes lab", :url => "https://github.com/stujo/ruby-classes-lab")
railslink21 = Link.create!(:title => "Gluten Free Exercise", :url => "https://gist.github.com/neurosaurus/197be8c4c0bdaf978871")
railslink22 = Link.create!(:title => "Debugging & Exercise", :url => "https://draftin.com/documents/298401?token=3BTDBiAReQGXSGKLJjDpzZsOS_p-wRsmLlPrcXCUhziKsIl0EKQWhPUwOJqOdVdk7-ORLPqmjYevf7gf22sjBkw")
railslink23 = Link.create!(:title => "Inheritance", :url => "https://draftin.com/documents/225498?token=6yYpUzjJRYu1DjI1OI3Qirnte6iyO7PLAW7yVcc3mN3ylPPOZuEHzisKft2Y0pnyHWMvmk42ElFuhEWM_0_BwH4")
railslink24 = Link.create!(:title => "Mini-Project HappiTrails", :url => "https://github.com/wdi-sf-march-2014/HappiTailsMiniProject")
railslink25 = Link.create!(:title => "Rental App Code Along", :url => "https://gist.github.com/jackieiscool/8165f4f9b9cd877b5394")
railslink26 = Link.create!(:title => "Quiz1", :url => "https://gist.github.com/spencereldred/899def2ee94cf769dfc9")
railslink27 = Link.create!(:title => "Tic Tac Toe lab", :url => "https://draftin.com/documents/299516?token=EfREJQIsHxwJabU7LZ2OUf7wHTpdf4jcySlbdHzSc1eOQlOJ2MDefQdxACK8fzfV_1uy4d-GR8IJ-h5zlNcn1Y8")
railslink28 = Link.create!(:title => "Rspec Lesson note", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/rspec/rspec_tests_revised.md")
railslink29 = Link.create!(:title => "Rspec lesson lab", :url => "https://github.com/wdi-sf-march-2014/notes/tree/master/rspec/lab")
railslink30 = Link.create!(:title => "Intro to Algorithms", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/IntroToAlgorithms/IntroToAlgorithms.md")
railslink31 = Link.create!(:title => "Algorithms lab", :url => "https://github.com/wdi-sf-march-2014/algorithms-ruby-lab")
railslink32 = Link.create!(:title => "Warm up Exercise-Palindromes", :url => "https://gist.github.com/DelmerGA/10742738")
railslink33 = Link.create!(:title => "Blocks & Iterators", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/BlocksIteratorsAndBeyond/blocks_iterators_and_beyond.md")
railslink34 = Link.create!(:title => "Intro to the Web Lesson", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/IntroToWeb/intro_to_web_resources.md")
railslink35 = Link.create!(:title => "Intro to Web Exercise", :url => "https://github.com/wdi-sf-march-2014/curl_scavenger_hunt")
railslink36 = Link.create!(:title => "Blocks & Iterators lab", :url => "https://github.com/wdi-sf-march-2014/sorted_array_with_iterators/tree/master")
railslink37 = Link.create!(:title => "Warm upExercise", :url => "https://gist.github.com/DelmerGA/10908344")
railslink38 = Link.create!(:title => "Sinatra notes", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/Sinatra/sinatra.md")
railslink39 = Link.create!(:title => "Sinatra calculator Exercise", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/Sinatra/sinatra_calculator.md")
railslink40 = Link.create!(:title => "APIs and JSON", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/APIsAndJSON/apis_and_json.md")
railslink41 = Link.create!(:title => "OMDB lab", :url => "https://github.com/wdi-sf-march-2014/Sinatra_API_Lab")
railslink42 = Link.create!(:title => "Intro to the DOM & CSS", :url => "https://draftin.com/documents/304053?token=Gg-hQ3od5il6G4YVplwiPksUaEWgS_k2k0r_HZnZU-JDqNIMTjzbqPYvcr9Ji7__GxKtYBr8A2_aVy3DtzvZxyI")
railslink43 = Link.create!(:title => "Sinatra2", :url => "https://github.com/wdi-sf-march-2014/notes/blob/master/Sinatra_day_2/more_sinatra.md")
railslink44 = Link.create!(:title => "HTML CSS", :url => "https://draftin.com/documents/304053?token=Gg-hQ3od5il6G4YVplwiPksUaEWgS_k2k0r_HZnZU-JDqNIMTjzbqPYvcr9Ji7__GxKtYBr8A2_aVy3DtzvZxyI")
railslink45 = Link.create!(:title => "Mini-Project-HappiTails", :url => "https://github.com/wdi-sf-march-2014/Sinatra-Movie-App-Part-Deux-Mini-Project/tree/master")
railslink46 = Link.create!(:title => "Warm up Binary Search", :url => "https://github.com/wdi-sf-march-2014/notes/tree/master/WarmUps/Methods/BinarySearch")


railslink1.tags.create!(:name => "Rails Guide")
railslink2.tags.create!(:name => "stackoverflow")
railslink3.tags.create!(:name => "PostGres")
railslink4.tags.create!(:name => "Steps for Installfest")
railslink6.tags.create!(:name => "Git Lesson")
railslink7.tags.create!(:name => "Ruby Overview, Part1")
railslink8.tags.create!(:name => "Ruby Overview, Part2")
railslink9.tags.create!(:name => "Living in the Command Line")
railslink10.tags.create!(:name => "Intro to Ruby Lesson")
railslink11.tags.create!(:name => "Intro to Ruby Lab")
railslink12.tags.create!(:name => "Into to Git notes")
railslink13.tags.create!(:name => "Git Lab")
railslink14.tags.create!(:name => "Git clone lab")
railslink15.tags.create!(:name => "Arrays & Hashes")
railslink16.tags.create!(:name => "Arrays & Hashes lab")
railslink17.tags.create!(:name => "Method & Blocks notes")
railslink18.tags.create!(:name => "Method & Blocks Exercises")
railslink19.tags.create!(:name => "Objects & Classes")
railslink20.tags.create!(:name => "Objects & Classes lab")
railslink21.tags.create!(:name => "Gluten Free Exercise")
railslink22.tags.create!(:name => "Debugging & Exercise")
railslink23.tags.create!(:name => "Inheritance")
railslink24.tags.create!(:name => "Mini-Project HappiTrails")
railslink25.tags.create!(:name => "Rental App Code Along")
railslink26.tags.create!(:name => "private")
railslink27.tags.create!(:name => "Tic Tac Toe lab")
railslink28.tags.create!(:name => "Rspec Lesson note")
railslink29.tags.create!(:name => "Rspec lesson lab")
railslink30.tags.create!(:name => "Intro to Algorithms")
railslink31.tags.create!(:name => "Algorithms lab")
railslink32.tags.create!(:name => "private")
railslink33.tags.create!(:name => "Blocks & Iterators")
railslink34.tags.create!(:name => "Intro to the Web Lesson")
railslink35.tags.create!(:name => "Intro to Web Exercise")
railslink36.tags.create!(:name => "Blocks & Iterators lab")
railslink37.tags.create!(:name => "private")
railslink38.tags.create!(:name => "Sinatra notes")
railslink39.tags.create!(:name => "Sinatra calculator Exercise")
railslink40.tags.create!(:name => "APIs and JSON")
railslink41.tags.create!(:name => "OMDB lab")
railslink42.tags.create!(:name => "Intro to the DOM & CSS")
railslink43.tags.create!(:name => "Sinatra2")
railslink44.tags.create!(:name => "HTML CSS")
railslink45.tags.create!(:name => "Mini-Project-HappiTails")
railslink46.tags.create!(:name => "Warm up Binary Search")
railslink2.tags.create!(:name => "private")
railslink3.tags.create!(:name => "Tic Tac Toe lab")
railslink4.tags.create!(:name => "Rspec Lesson note")
railslink5.tags.create!(:name => "Rspec lesson lab")
railslink6.tags.create!(:name => "Intro to Algorithms")
railslink7.tags.create!(:name => "Algorithms lab")
railslink8.tags.create!(:name => "private")
railslink9.tags.create!(:name => "Blocks & Iterators")


commenta = railslink1.comments.create!(:content => "Shaq is awesome")
commentb = railslink2.comments.create!(:content => "Taylor likes to be the boss")
commentc = railslink2.comments.create!(:content => "The team is becoming awesome")
commentd = commenta.comments.create!(:content => "Rahul needs to calm down")